### PR TITLE
Open Rpt File

### PR DESCRIPTION
**Pull request by simon84**
Hi,

I added the command `language-arma-atom:open-rpt-file`, which opens the rpt-file and automatically scrolls down. The default rpt-file folder is `%localappdata%\\Arma 3\\` which can be set in the package settings panel. I will add this functionality to a toolbar system called [`tool-bar`](https://atom.io/packages/tool-bar), which seems to be very easy. What is your opinien about that?

### CODE REVIEW

**Comment by jokoho48** [comment]
cool like it did you know if it could be posible to add the build/make tool to?(if the Current Project is ACE or CBA use this tools)

**Comment by simon84** [comment]
you mean the ace3 building script? should be possible. maybe it is better to configure this in the ace project, not in the package itself. but i need more time to think about it.

**Comment by jokoho48** [comment]
ok awsome thanks :+1:

**Comment by jonpas** [comment]
This branch contains commits for your autocompletion branch, you should create a new branch from the master branch.

> I will add this functionality to a toolbar system called tool-bar, which seems to be very easy. What is your opinien about that?

As long as it doesn't make that package a requirement I see no issues with it.

**Comment by simon84** [comment]
Ok, I created a new branch and pr (#17). This pr can be closed.

**Pull request closed without merging**
