### PR TITLE
Fix: number in local variables after first underscore

### LINKED ISSUE #33: Loacal Variables starting with numbers don't autocomplete
if you use a variable like
`_40mmGrenade = "AwsomeVar";`
the syntax highlighter not register it

### PR DESCRIPTION
**Pull request by simon84**
This should fix #33.

### CODE REVIEW

**Comment by jonpas** [comment]
:+1:

**Comment by kymckay** [comment]
Why was this merged? This is invalid syntax

**Comment by kymckay** [comment]
Although, now I'm doubting myself. When I wrote that regex I did that on purpose because I was under the impression that this was invalid syntax :stuck_out_tongue:

If it is valid, the proper fix would be to remove the whole `[_a-zA-Z]` section

**Comment by kymckay** [comment]
Yep, never mind it's totally valid :sweat_smile:

I think I must have gotten tripped up reading this: https://community.bistudio.com/wiki/Identifier

I don't have this git repo set up locally atm, if someone wants to just remove the whole `[_a-zA-Z0-9]` section I'd appreciate it :+1: (You'll also need to make the `*` a `+`)

**Comment by jonpas** [comment]
@SilentSpike so `"match": "\\b_\\w+\\b"` is correct?

And I merged it because it worked. :grin:

**Comment by simon84** [comment]
Yeah this should be much better. It has the same effects.

**Comment by jonpas** [comment]
Done, thanks.

**Pull request merged**
