### PR TITLE
Add ACE3 public functions

### PR DESCRIPTION
**Pull request by Cuel**
Filter ace3 function files for those marked public. Adds grammar and autocomplete
- Note: Takes ace3 root directory as argument. (should use release branch)

### CODE REVIEW

**Comment by thojkooi** [comment]
Hi @Cuel, thanks for your PR. Could you please resolve the merge conflicts on this PR?

**Comment by jonpas** [comment]
Should we lowercase `ace` in function name as well? It's documented like that in example in header (and it looks nicer) @Glowbal ?

**Comment by thojkooi** [comment]
Yes, let's lower case it.

**Comment by Cuel** [comment]
What's the merge conflicts exactly? I can't see any

Edit:

```
-  "version": "2.1.2",
 +  "version": "2.2.0",
```

Was that it? I really need to stop using github desktop

**Comment by jonpas** [comment]
You were on an older commit. And yes, start using CLI like a real man.

**Comment by Cuel** [comment]
Lowercase'd

**Pull request merged**
