### PR TITLE
Added Conditional Structures, Loops, and CBA PFH Add Snippets

### PR DESCRIPTION
**Pull request by jonpas**
Some more snippets that used to be in sublime packages and more, let me know which are fit and which not and I will remove/add accordingly. Or name changes or anything.
## Conditional Structures

if statement (`if`):

```
if (CONDITION) then {
    //code
};
```

if-else statement (`if-else`):

```
if (CONDITION) then {
    //code
} else {
    //code
};
```

if-else assignment (`if-else_assign`):

```
VARIABLE = if (CONDITION) then {ASSIGNMENT_TRUE} else {ASSIGNMENT_FALSE};
```

switch statement (`switch`):

```
switch (VARIABLE) do {
    //cases (insertable by snippet)
};
```

case block of switch (`case_switch`):

```
case (VALUE): {
    //code
};
```

default block of switch (`default_switch`):

```
default {
    //code
};
```
## Loops

forEach loop (`forEach`):

```
{
    //code
} forEach ARRAY;
```

C-like for loop (`for_c`):

```
for [{BEGIN}, {CONDITION}, {STEP}] do {
    //code
};
```

for-from-to loop (`for_from_to`):

```
for VALUE from STARTVALUE to ENDVALUE do {
    //code
};
```

for-from-to-step loop (`for_from_to_step`):

```
for VALUE from STARTVALUE to ENDVALUE step STEP do {
    //code
};
```

while loop (`while`):

```
while {CONDITION} do {
    //code
};
```
## CBA PFH Add

CBA PerFrameHandler Add (`cba_pfh_add`):

```
[{FUNCTION/CODE}, DELAY, [PARAMETERS]] call CBA_fnc_addPerFrameHandler;
```

### CODE REVIEW

**Comment by jonpas** [comment]
Removed `waitUntil` snippet as I deem it not worth (it just added braces really).

**Comment by thojkooi** [comment]
:+1:

**Comment by bux** [comment]
I'd like it more if the "switch" snippets would all start with `switch`.
- `switch`
- `switch_case`
- `switch_default`

**Comment by thojkooi** [comment]
I disagree, I think it makes more sense this way as you write a new `case` block. But we can add another prefix for those easily.

**Comment by jonpas** [comment]
I disagree as well, it has to be good for typing, not looks.

> But we can add another prefix for those easily.

Relatively. :p

**Pull request merged**
