### PR TITLE
Fix missing commands

### PR DESCRIPTION
**Pull request by simon84**
and changed wiki source to "Category: Scripting Commands".

Remarks: the command in "in" is to short for code completion. Its in the list, but will not show up in the code completion drop down list. 

Related to #53 and #54

### CODE REVIEW

**Comment by jonpas** [comment]
> Its in the list, but will not show up in the code completion drop down list. 

That is configurable in Atom's settings.

**Comment by jokoho48** [comment]
did this fix missing command step?

**Comment by simon84** [comment]
no. But I would suggest to put this command to the class "control structures". I change it.

**Comment by simon84** [comment]
Ok, i found some missing commands. I'm checking it.

**Comment by simon84** [comment]
ok. Now, everything should be fine. I checked the syntax highlighting against the site:
https://community.bistudio.com/wiki/Category:Scripting_Commands

**Comment by jonpas** [comment]
Thanks again!

**Pull request merged**
