### PR TITLE
Add macros for crate configs

### PR DESCRIPTION
**Pull request by dedmen**
Adds macros to add items to crates.
From: https://github.com/acemod/ACE3/blob/master/addons/main/script_macros.hpp#L50

### CODE REVIEW

**Review by jonpas — APPROVED** [review]
Looks good to me, @Glowbal ?

**Comment by thojkooi** [comment]
:+1: Thanks @dedmen

**Review by jonpas — CHANGES_REQUESTED** [review]
Actually, all those macros are used with a trailing semi-colon in ACE3, eg. `MACRO_ADDWEAPON(ACE_MX2A,1);`, should be same here.

**Comment by dedmen** [comment]
I actually did that mistake in my code and used commas to seperate them :D Ill fix

**Review by jonpas — APPROVED** [review]

**Comment by jonpas** [comment]
Thank you!

**Pull request merged**
