### PR TITLE
Changing to autocompletion plus

### PR DESCRIPTION
**Pull request by simon84**
Hi,

I changed the automatic completion to autocompletion-plus which enables nice formatting of function documentation. Additionally, I wrote a python-script to crawl the bi-wiki for command description. Now all BI commands are available in autocompletion with their parameters and documention/link.

Simon aka BadGuy

### CODE REVIEW

**Comment by jokoho48** [comment]
why you remove the CBA Macros?

**Comment by jonpas** [comment]
@jokoho48 he didn't, just moved them into `settings/language-sqf.json`

I will test this in a bit.

**Comment by jokoho48** [comment]
aha ok

**Comment by kymckay** [comment]
Very nice work :+1:

**Comment by jonpas** [comment]
I wonder, is it somehow possible to not have everything in one single huge file (`settings/language-sqf.json`) but rather spread somehow? Or do JSON and Atom not allow this?

**Comment by simon84** [comment]
@jonpas This would be nice. I don't know. I'm relativly new to the atom.io community (joined last week, its a really nice editor)

I would like to add some more features, like a command to open latest rpt-file. What do you think?

**Comment by jonpas** [comment]
We can always split it if we find a way.

That would be great, do it in a separate PR and we'll see how it works. ;)

**Comment by kymckay** [comment]
Yep, that is a feature Glowbal and myself have discussed since we both switched to Atom from poseidon recently. Definitely something I'm interested in adding.

**Comment by kymckay** [comment]
With the addition of this .py file you can delete the commandList.txt file under rsc :smile:

**Comment by simon84** [comment]
We/I have to modify the python file. It's not complete yet. My dream is to have one File which generates all autocompletion snippets. At the moment I can only parse the wiki commands.

**Comment by jonpas** [comment]
Did a quick test, autocompletion-plus is indeed very nice!

I found a problem with tab selection inside tab selection, eg:
`"snippet": "actionKeysNames ${1:[${2:userAction}, ${3:maxKeys}]}$0",`
Only `userAction` comes up as a tab selection.

I also don't see the purpose of having `$0` at the end of each command snippet, it lets you use tab directly to go to the end if you don't type anything (which almost never happens) and if it's in its own line you can just hit `End` to go to the end as well. Am I missing something?

**Comment by simon84** [comment]
@jonpas in my editor its working. First I get `[userAction, maxKeys]`, then `userAction` and after that `maxKeys`. At the end you can tab-out of the command. So you don't have to use <kbd>End</kbd>.

**Comment by jonpas** [comment]
Ohhh, my bad, there are different auto-completion commands for both types, one with array and one with just `userAction`. I am blind as always!

> At the end you can tab-out of the command. So you don't have to use End.

It doesn't hurt to keep it of course, I was just wondering if there is anything extra to it.

This PR looks good to me so far, ideal would be if we could split up that giant file of course.

**Comment by simon84** [comment]
@jonpas in my first version I didn't added the `$0` at the end. But then I saw this pattern in some language packages. So I thought this is common practice.

**Comment by jonpas** [comment]
Good to know :+1:

**Comment by jonpas** [comment]
@simon84 I may have found something useful for splitting the large JSON file into multiple files, if you are up to some experimentation. http://spacetelescope.github.io/understanding-json-schema/structuring.html

If not we will merge this and then look into it.

**Comment by thojkooi** [comment]
Just tried it. :+1: Thank you.

**Pull request merged**
