### PR TITLE
Autosuggestions for CBA and ACE are now optional

### PR DESCRIPTION
**Pull request by publicJorn**
Note that the `/settings` and `/snippets` directories are now git-ignored. The new -Available directories are now leading. On first package activation the above directories will be recreated and filled the bis files and with whatever add-ons are chosen.

Btw, I could only find 2 references to generated settings files. For `language-sqf-functions-ace3.json` and `language-sqf-functions-bis.json`. Is it correct that all other .json settings and snippets are typed manually?

### CODE REVIEW

**Comment by thojkooi** [comment]
Thanks @publicJorn, we will review this soon. All files related to syntax highlighting and auto completion are auto generated iirc.

**Comment by jonpas** [comment]
> Is it correct that all other .json settings and snippets are typed manually?

Negative, there are python scripts for others. I can take care of those. 

Will review later today.

**Comment by jonpas** [comment]
I get the following error when clicking "Settings" on the package:

```
Uncaught Error: Cannot find module 'copy-newer'
module.js:340
Hide Stack Trace
Error: Cannot find module 'copy-newer'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///E:/Arma 3/Tools/language-arma-atom/index.coffee:2:13)
    at Object.<anonymous> (file:///E:/Arma 3/Tools/language-arma-atom/index.coffee:1:1)
    at Module._compile (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateConfig (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:222:12)
    at PackageDetailView.module.exports.PackageDetailView.activateConfig (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:220:26)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:163:12)
    at PackageDetailView.module.exports.PackageDetailView.loadPackage (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:175:21)
    at PackageDetailView.module.exports.PackageDetailView.initialize (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:150:19)
    at PackageDetailView.View [as constructor] (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
    at PackageDetailView.ScrollView [as constructor] (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\atom-space-pen-views\lib\scroll-view.js:12:47)
    at new PackageDetailView (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:42:54)
    at C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:269:22
    at SettingsView.module.exports.SettingsView.getOrCreatePanel (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:274:19)
    at SettingsView.module.exports.SettingsView.showPanel (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\settings-view.js:320:24)
    at space-pen-div.<anonymous> (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\package-card.js:276:83)
    at space-pen-div.jQuery.event.dispatch (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-div.elemData.handle (C:\Users\name\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

The Python scripts for generating the other files just put them in that folder so they have to be moved manually anyways. I might update that, one day.

**Comment by publicJorn** [comment]
Hi @jonpas, the error is because I'm using an npm dependency. Should have noticed that.  We developers have to manually install it by typing `npm install` in the package root. I believe you can also use the [command pallette](http://stackoverflow.com/questions/36810276/installing-package-dependencies-in-atom). 

The package consumers don't have to do anything. If the package gets updated/installed it should fetch npm dependencies. 

As for the python scripts, could that be as easy as prepending ~~`../setings/`~~ `../setingsAvailable/` to the file names, ~~all the way at the bottom of~~ [for example in this file](https://github.com/acemod/language-arma-atom/blob/master/rsc/parseOperators.py#L180)?

**Comment by jonpas** [comment]
Ah I see, yes it might be.

**Comment by jonpas** [comment]
I have added "requires restart" to the description and renamed it to "autocomplete". Thank you for the contribution.

**Comment by publicJorn** [comment]
Thanks for taking it!

**Pull request merged**
