### PR TITLE
converted cson to json

### PR DESCRIPTION
**Pull request by bux**
Thanks to https://github.com/bevry/cson

### CODE REVIEW

**Comment by bux** [comment]
That's just a raw convert of the cson files. Haven't tested it yet, because I'm not at home.

**Comment by MikeMatrix** [comment]
What's the intent behind this exactly?

**Comment by bux** [comment]
Coffescript is the root of all evil and should burn in hell.

**Comment by MikeMatrix** [comment]
I love coffescript and I'll fight you to the death :D

**Comment by bux** [comment]
Go away filthy demon and take your whitespace and new line scripting language and go back to the dark, rotten hole of where you emerged. :smile:

**Comment by thojkooi** [comment]
Yay! :+1:

**Comment by jonpas** [comment]
Missing newlines at the end of files (aren't you using Atom that will do it automatically on save).

**Comment by bux** [comment]
@jonpas I've been using this: https://github.com/bevry/cson (it's just a converter)

**Comment by jonpas** [comment]
Yeah, I am just saying there are no newlines at the end of files. Not like it matters, it just jumped into my eyes (i hate that "no newline at end of file"  GitHub icon :grinning: ).

**Pull request merged**
